import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex sm:flex-row flex-col min-h-screen space-y-3 sm:space-y-0`}
      >
        <Sidebar />
        <div className="border border-gray-300 w-full px-2 sm:px-4 space-y-5 min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
