import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { StoreProvider } from "./StoreProvider";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex w-full min-h-screen items-stretch`}
      >
        <Sidebar />
        <div className="pl-3 w-full flex flex-col min-h-screen overflow-y-auto">
          <Navbar />
        <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
